import type * as CSS from 'csstype'

export const positioning: Array<keyof CSS.StandardPropertiesHyphen> = [
  'isolation',
  'position',
  'z-index',
  'inset',
  'inset-block',
  'inset-block-start',
  'inset-block-end',
  'inset-inline',
  'inset-inline-start',
  'inset-inline-end',
  'top',
  'right',
  'bottom',
  'left',
  'zoom',
  'transform-origin',
  'transform-box',
  'transform-style',
  'transform',
  'translate',
  'rotate',
  'scale',
  'offset-path',
  'offset-distance',
  'offset-rotate',
  'anchor-name',
  'anchor-scope',
  'position-anchor',
  'position-area',
  'position-visibility',
  'position-try',
  'position-try-order',
  'position-try-fallbacks',
]
