import type * as CSS from 'csstype'

export const transition: Array<keyof CSS.StandardPropertiesHyphen> = [
  'transition',
  'transition-delay',
  'transition-timing-function',
  'transition-duration',
  'transition-property',
  'transition-behavior',
  'animation',
  'animation-name',
  'animation-duration',
  'animation-play-state',
  'animation-timing-function',
  'animation-fill-mode',
  'animation-delay',
  'animation-iteration-count',
  'animation-direction',
  'animation-timeline',
  'animation-range',
  'animation-range-start',
  'animation-range-end',
  'animation-composition',
  'timeline-scope',
  'scroll-timeline',
  'scroll-timeline-name',
  'scroll-timeline-axis',
  'view-transition-class',
  'view-timeline',
  'view-timeline-name',
  'view-timeline-axis',
  'view-timeline-inset',
  'view-transition-name',
]
