const transition = [
  'transition',
  'transition-delay',
  'transition-timing-function',
  'transition-duration',
  'transition-property',
  'animation',
  'animation-name',
  'animation-duration',
  'animation-play-state',
  'animation-timing-function',
  'animation-fill-mode',
  'animation-delay',
  'animation-iteration-count',
  'animation-direction',
  'animation-timeline',
  'timeline-scope',
  'scroll-timeline-name',
  'scroll-timeline-axis',
  'scroll-timeline',
  'view-timeline-name',
  'view-timeline-axis',
  'view-timeline',
  'view-timeline-inset',
]

module.exports = { transition }
