name: Checks

on:
  workflow_call: {}

jobs:
  checks:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Run tests
            command: test
          - name: Lint code
            command: check:lint
          - name: Check types
            command: check:types
          - name: Check formatting
            command: check:format
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup
        uses: ./.github/actions/setup

      - name: ${{ matrix.name }}
        run: pnpm run ${{ matrix.command }}
