name: Release

on:
  push:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read

jobs:
  checks:
    uses: ./.github/workflows/_checks.yaml

  build:
    needs: [checks]
    uses: ./.github/workflows/_build.yaml

  release:
    needs: [build]
    name: Release
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: '26'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Download build artifact
        uses: actions/download-artifact@v8
        with:
          name: ${{ needs.build.outputs.artifact-name }}
          path: ${{ github.workspace }}/${{ needs.build.outputs.build-output-pathname }}

      - name: Create release PR or publish
        uses: changesets/action@v1
        with:
          version: pnpm run version
          publish: pnpm run release
          commit: 'chore(release): version packages'
          title: 'chore(release): version packages'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
